### ISSUE TITLE
How to run this component with React Native 0.56?

### ISSUE THREAD

**Issue by gitowiec** [react-native-community/async-storage#137]
## You want to:  
I would like to use async-storage in my RN 0.56 project, but I have compilation error saying

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/user/workspace/project/mobile/node_modules/@react-native-community/async-storage/android/build.gradle' line: 4
> 
> * What went wrong:
> A problem occurred evaluating project ':@react-native-community_async-storage'.
> > Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
> 

What I determined is that async-storage in its package.json keeps 

>   "peerDependencies": {
>     "react": "^16.0",
>     "react-native": ">=0.57"
>   },

Is it a must minimal version of RN? Or is there any way I could run it with 0.56?

Excuse for my naive question but I am new to RN and its dependencies on native components of Android framework (eg gradle).

**Comment by Krizzu** [comment]
Hi @gitowiec ,

This issue is related to a version of Gradle you use in the project:

```
Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
```

Apparently, your version is too low. Please check `buildscript` in your `android/build.gradle` file. There should be `classpath 'com.android.tools.build:gradle:X.X.X'` entry in `dependencies` block. Can you provide what the version (`X.X.X` here) is?

**Comment by gitowiec** [comment]
Thanks for rapid response,
The version is 2.3.3
And here is the rest of that file (in case of whatever)
````
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            // Local Maven repo containing AARs with JSC library built for Android
            url "$rootDir/../node_modules/jsc-android/dist"
        }
    }
}

ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 21
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

subprojects {
  project.configurations.all {
      afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.2'
            }
        }
    }
     resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.android.support'
              && !details.requested.name.contains('multidex') ) {
           details.useVersion "26.0.2"
        }
     }
  }
}
````

**Comment by gitowiec** [comment]
I remeber that I once tried to upgrade Gradle by tinkering with the content of `android/gradle/wrapper/gradle-wrapper.properties` (due to the some other issue). And after changing  `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5.1-all.zip` prop I could no more build my app.

**Comment by Krizzu** [comment]
@gitowiec `run-android` is using Gradle wrapper ([relevant code here](https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.js#L90)).

You have two options:
- (recommended) Upgrade to a higher version of Gradle wrapper and use higher version of build tools
- Add `maven { url 'https://maven.google.com' }` to `android/build.gradle` dependency block, instead of `google()`


If you're going to upgrade gradle, try version:

1. in `android/gradle/wrapper/gradle-wrapper.properties`:

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

2. in `android/build.gradle`, `buildscripts`'s dependency block:

`classpath 'com.android.tools.build:gradle:3.3.2'`


thanks.

**Comment by gitowiec** [comment]
I have a hard time with this. After changing buildscript dependencies classpath to 'com.android.tools.build:gradle:3.3.0' I learnt (here https://stackoverflow.com/questions/54288307/in-a-reactnative-project-why-my-android-gradle-versions-are-different) that this version numbers mean two different programs. In gradle-wrapper.properties is Gradle version (distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip), and in build.gradle is Android Gradle Plugin

As I stated here I put 3.3.0 in build.gradle and 4.10.1 in the other file. After invoking react-native run-android I got  

````
* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
````
And after I changed Android Gradle Plugin back to 2.3.3 I got:

````
FAILURE: Build failed with an exception.

* Where:
Build file '/home/marek/workspace/vatnumberchecker/mobile/node_modules/@react-native-community/async-storage/android/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':@react-native-community_async-storage'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
````
So I have to accept never SDK (which I don't want to because I want my app to develop on Android 6 emulator) or another thing which I don't understand :)

**Comment by Krizzu** [comment]
@gitowiec Gradle wrapper version and build tools version do not match with each other, so you don't have to worry about that.

In order to install build tools 28.0.3 (required by gradle) you have to accept the licenses. It'd be the easiest to run it through Android Studio, which installs necessary SDK for ya. ([and here's how to do it manually](https://stackoverflow.com/a/43003932/3510245)).

**Comment by gitowiec** [comment]
And if I do what You recommend (Upgrade to a higher version of Gradle wrapper and use higher version of build tools), will I still be able to compile for Android 6?

**Comment by Krizzu** [comment]
@gitowiec Yes. You decide the lower boundary with `minSdkVersion` number in your `app/build.gradle`

**Comment by Krizzu** [comment]
I hope the issue has been resolved, so closing this one down.
