### ISSUE TITLE
Installation Cocoapods adds outdated React dependency 0.11

### ISSUE THREAD

**Issue by nielskrijger** [react-native-community/async-storage#144]
## Current behavior

I followed these manual instructions for pod linking on a new project:
https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md

I ended up with a podfile like this:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AsyncStorageProject2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
end
```

The generated podfile.lock includes a dependency on react 0.11:

```
PODS:
  - React (0.11.0):
    - React/Core (= 0.11.0)
  - React/Core (0.11.0)
  - RNCAsyncStorage (1.5.0):
    - React
```

## Expected behavior

No react dependency at all;
or an up-to-date react version;
or instructions (here https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md) explaining how to link the react pod in your podfile with the correct node_modules version (i.e. the one installed by package.json)
or some sort of warning of this default behaviour.

## Repro steps

- Create new project
- Follow pod linking instructions https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md

## Environment

- **Async Storage version**: 1.5.0
- **React-Native version**: 0.59.9
- **Platform tested**: iOS

## Background info

This ticket is the first issue I encountered in a chain of 3 or 4 errors with the pod install on react-native 0.59.9. I was eventually defeated by this one: https://github.com/facebook/react-native/issues/24192

With manual project linking it worked like a charm!

**Comment by tido64** [comment]
You do need to use CocoaPods for everything, or not use it at all. The React dependency needs to be there otherwise Xcode will not build React and RNCAsyncStorage in the correct order. We have some words about that in the [troubleshooting guide](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Troubleshooting.md#ios-fatal-error-reactrctbridgemoduleh-file-not-found). What you're seeing there is an ancient version of React that was pushed to the CocoaPods repo before they stopped using it as source.

Thanks for reporting this. We will update the instructions to be more clear.

cc @Krizzu

**Comment by Krizzu** [comment]
Hi @nielskrijger,

Could you post your `Podfile`?
