### ISSUE TITLE
Default branch in this repo

### ISSUE THREAD

**Issue by friederbluemle** [react-native-community/async-storage#212]
Having a _default_ branch called `LEGACY` is rather unusual. I understand the intention is to have **two concurrently running development paths** (since there _is_ also a diverged `master` branch).

Just a suggestion:

- Keep the default branch at the Git standard `master` (where current releases are coming from)
- Have a separate branch `next` with ongoing work (potentially incompatible) for the upcoming version

It's tricky, but doable to change this without force pushing in the current repo. Let me know if this is something you might consider, otherwise please feel free to just close the issue :)

**Comment by Krizzu** [comment]
Hi @friederbluemle 	,
Normally, I'd start with naming you suggested, but in Async Storage perspective, these two branches are completely different libraries. 

Once `master` branch (Async Storage v2) is released, I'm going to set it back as the default branch so that the `LEGACY` can go into maintain mode. This would be more difficult if I'd keep current version at `master`.


Thanks for your insight 🙌

**Comment by friederbluemle** [comment]
Ooh okay, I did not know. If it's really two _completely different libraries_, how about using two different repositories for them? :)

**Comment by Krizzu** [comment]
Because it's still, an AsyncStorage module, but now it's divided into core + different storages, supporting different cases and platforms - all maintained in monorepo.

**Comment by friederbluemle** [comment]
Thanks for explaining @Krizzu 👌
