### ISSUE TITLE
Wrong the value is not a string warning on multiRemove

### ISSUE THREAD

**Issue by Bardiamist** [react-native-community/async-storage#267]
## Current behavior

Warning

## Expected behavior

No warning

## Repro steps

```
AsyncStorage.setItem('a', '1').then(() => {
  AsyncStorage.multiRemove(['a']);
});
```

## Environment

- **Async Storage version**:  1.7.0
- **React-Native version**: 0.61.5
- **Platform tested**: iOS
- **Logs/Error that are relevant**:
[AsyncStorage] The value for key "a" is not a string. This can lead to unexpected behavior/errors. Consider stringifying it.
Passed value: 0
Passed key: a

**Comment by fontesrp** [comment]
I'm also seeing this warning pop up when I call `multiRemove` with keys that currently have no value stored.

So, for me, on version `1.7.0` the following happens:

```jsx
AsyncStorage.setItem('obj1', '{prop:"val"}')
  .then(() => AsyncStorage.multiRemove(['obj1']))
  .then(() => AsyncStorage.multiRemove(['obj1']))
```

On the second call to `multiRemove`, I get a yellow box saying

```
[AsyncStorage] The value for key "obj1" is not a string. This can lead to unexpected behaviour/errors.
Consider stringifying it.
Passed value: 1
Passed key: obj1
```

Since I'm not setting the value of `obj1`, this should not appear, right?

**Comment by Krizzu** [comment]
Will look into it, thanks for reporting.
