### ISSUE TITLE
Can't save anything to storage

### ISSUE THREAD

**Issue by rolandleth** [react-native-community/async-storage#294]
## Current behavior

I get an error when trying to save anything but a string.

## Expected behavior

To be able to save objects.

## Repro steps

I tried saving the object from the docs:

```
const legacyStorage = new LegacyStorage()

type StorageModel = {
  user: {
    name: string
    age: number
  }
}

const storage = AsyncStorageFactory.create<StorageModel>(legacyStorage)

async function saveItem() {
  const myUser = {
    name: 'John',
    age: 22
  };
  
  await storage.set('user', myUser);
}

// Somewhere else...

saveItem()
```

## Environment

- **Async Storage version**: ^2.0.0-rc.2
- **React-Native version**: 0.61.5
- **Platform tested**: iOS
- **Logs/Error that are relevant**:

```
WARN  [AsyncStorageLegacy] The value for key "user" is not a string. This can lead to unexpected behavior/errors. Consider stringifying it.
Passed value: [object Object]
Passed key: user
```

If I change `StorageModel` to 

```
type StorageModel = {
  user: string
}
```

and stringify the object before saving, it works (and I can also read it back, as a string, of course). But that's not really what I'd expect 😞

**Comment by tido64** [comment]
@Krizzu correct me if I'm wrong but we currently do not have any plans to support this scenario. The only way we would be able to support this is if we stringified the object behind the scenes. This will however open up different issues like losing data. In my opinion, this behaviour is more explicit, and it puts the responsibility of correctly serializing objects on the consumer. If you have ideas on how we can solve this, we're open to suggestions.

Perhaps we can set expectations with better documentation?

**Comment by rolandleth** [comment]
Thanks for the quick reply!

Sadly, I don’t have too much JS experience to acknowledge all the implications of serialization and/or have any suggestions; I’d probably stringify it. 

What about using an SQLite database, like on Android? If it’s possible there, should be possible here as well, since iOS supports it as well?

> Perhaps we can set expectations with better documentation?

If it’s truly no way to do it, I suppose so, because that piece of code definitely looks like it should save 🙃

**Comment by tido64** [comment]
On Android, we do in fact use SQLite underneat. On iOS, we have a different solution. The issue is really the fact that everything has to be serialized at some point in JS before it is passed to the native side. This is currently how React Native works in general, not just AsyncStorage. This may change with the Fabric rewrite but I haven't really looked into it yet.

I find the MDN entry on [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) is really useful. It has a section with examples on what gets returned (or doesn't) given different input.

**Comment by rolandleth** [comment]
Hmm, but for Android, doesn't a "serialization" happen to be able to save it in SQLite? Can't that same serialization logic be used for iOS too and use SQLite instead of documents?

**Comment by Krizzu** [comment]
@rolandleth Like @tido64 said - we don't serialize data implicitly, because of the data loss, so we rather expect to be given serialized data that we can store as string.

There's a work for v2 in progress, which allows for different storage implementation to be used. SQL for iOS would be something I'd look for in this version.

**Comment by rolandleth** [comment]
Oh, my bad, I misunderstood; I implicitly assumed (wrong) that because it's using SQLite, it's _also_ serializing the data somehow.

What would serialization require/imply? Following the example in the issue/docs, what would need to happen to `StorageModel` to be saved and how would it have to be passed in?

**Comment by tido64** [comment]
In React Native, all communication between JS and native occur over a bridge. When `AsyncStorage` wants to send data to the native side, where the actual storing of data occurs, the data is handed to the bridge. The bridge will serialize the data, pass it to native, deserialize the data, then forward it to the appropriate native module. While the bridge does its best to preserve as much data as possible, there are certain types of data it cannot distinguish between, leading to loss of meta data and sometimes data itself. This is a limitation in React Native. `AsyncStorage` tries to work around this by requiring strings to be passed.

Since `StorageModel` is fairly simple, you can rely on [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) to do the right thing.

**Comment by rolandleth** [comment]
OK, understood 👍🏻

Thanks for all the explanations!
